config/routes.rb
Rails.application.routes.draw do
  resources :admin_users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  get 'signin', to: 'sessions#new'
  get 'signup', to: 'admin_users#new'
  get 'signout', to: 'sessions#destroy'
  root 'users#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
	before_save { email.downcase! }
	before_create :generate_remember_token
	
	EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i

	validates :name, presence: true
	validates :email, presence: true, format: { with: EMAIL_REGEX }, uniqueness: { case_sensitive: false }

	has_secure_password
	validates :password, length: { minimum: 6 }

	def AdminUser.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def AdminUser.digest(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private

	def generate_remember_token
		self.remember_token = AdminUser.digest(AdminUser.new_remember_token)
	end

end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { email.downcase! }

	EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i

	validates :first, presence: { message: "name can't be empty" }
	validates :email, presence: true, format: { with: EMAIL_REGEX }, uniqueness: { case_sensitive: false }

end

app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController

  def new
  	@user = AdminUser.new
    redirect_to root_path if signed_in?
  end

  def create
  	@user = AdminUser.new(user_params)
  	if @user.save
      sign_in @user
  		flash[:success] = "Thank you for signing up!"
  		redirect_to root_path
  	else
      flash.now[:warning] = "An error occurred"
  		render 'new'
  	end
  end

  private

  def user_params
  	params.require(:admin_user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  	
  end

  def create
    user = AdminUser.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
			sign_in user
			redirect_to root_path
    else
      flash.now[:warning] = 'Invalid email/password'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
    @users = User.all
    if @users.empty? && signed_in?
      flash[:success] = flash[:success] if !flash[:success].blank?
      flash[:warning] = "There are currently no users in the database!"
      redirect_to new_user_path
    end
	end

  def new
  	@user = User.new
    redirect_to signin_path if !signed_in?
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		flash[:success] = "User created successfully!"
  		redirect_to users_path
  	else
      flash.now[:warning] = "An error occurred"
  		render 'new'
  	end
  end

  def edit
    @user = User.find(params[:id])
    redirect_to signin_path if !signed_in?
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "User updated successfully!"
      redirect_to users_path
    else
      render 'edit'
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    flash[:success] = "User deleted successfully!"
    redirect_to users_path
  end

  private

  def user_params
  	params.require(:user).permit(:first, :last, :email)
  end

end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		remember_token = AdminUser.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, AdminUser.digest(remember_token))
		self.current_user = user
	end

	def signed_in?
		!current_user.nil?
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		remember_token = AdminUser.digest(cookies[:remember_token])
		@current_user ||= AdminUser.find_by(remember_token: remember_token)
	end

	def sign_out
		current_user.update_attribute(:remember_token, AdminUser.digest(AdminUser.new_remember_token))
		cookies.delete(:remember_token)
		self.current_user = nil
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin_users/new.html.erb
<section class="row">
  <div class="col-md-6 col-sm-6 col-sm-offset-3 col-md-offset-3">
    <h1 class="center">Create a new account</h1>
    <%= form_for @user do |f| %>
     
      <%= f.label :name, "Full Name (required)" %>
			<%= f.text_field :name %>

			<%= f.label :email, "Email (required)" %>
			<%= f.text_field :email %>

			<%= f.label :password %>
			<%= f.password_field :password %>

			<%= f.label :password_confirmation, "Confirm Password" %>
			<%= f.password_field :password_confirmation %>

			<% if @user.errors.any? %>
				<% @user.errors.full_messages.each do |msg| %>
			  	<p class='error-messages'>
			  		<%= msg %>
			  	</p>
			  <% end %>
			<% end %>
     
      <%= f.submit "Create user", class: "btn btn-large btn-primary" %>
     
    <% end %>
  </div>
</section>

app/views/layouts/_form.html.erb
<%= f.label :first, "First Name (required)" %>
<%= f.text_field :first %>

<%= f.label :last, "Last Name" %>
<%= f.text_field :last %>

<%= f.label :email, "Email (required)" %>
<%= f.text_field :email %>

<% if @user.errors.any? %>
	<% @user.errors.full_messages.each do |msg| %>
  	<p class='error-messages'>
  		<%= msg %>
  	</p>
  <% end %>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "User Database Management", root_path, id: "name" %>
      <nav>
        <ul class="nav pull-right navbar-nav">
          <li><%= link_to "Home",    root_path %></li>
        <% if signed_in? %>
          <li><%= link_to "Sign out (#{current_user.name})", signout_path %>
        <% else %>
          <li><%= link_to "Sign in", signin_path %></li>
          <li><%= link_to "Sign up", signup_path %></li>
        <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Code Fellows' Rails Challenge</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<% flash.each do |k, v| %>
		<div class="alert alert-<%= k %>"><%= v %></div>
	<% end %>

	<%= yield %>

</body>
</html>

app/views/users/edit.html.erb
<section class="row">
  <div class="col-md-6 col-sm-6 col-sm-offset-3 col-md-offset-3">
    <h1 class="center">Edit user</h1>
    <%= form_for @user do |f| %>
     
      <%= render 'layouts/form', f: f %>
     
      <%= f.submit "Update user", class: "btn btn-large btn-primary" %>
     
    <% end %>
  </div>
</section>

app/views/users/index.html.erb
<% if signed_in? %>
	<section class="row">
		<div class="col-xs-12 col-md-8 col-sm-8 col-md-offset-2 col-sm-offset-2 col-lg-6 col-lg-offset-3">

		<h1 class="center">Current Users</h1>

		<span class="header center col-md-3 col-sm-3 col-xs-3">Name</span>
		<span class="header center col-md-5 col-sm-5 col-xs-5">Email</span>
		<span class="header center col-md-4 col-sm-4 col-xs-4">Actions</span>

		<% @users.each do |user| %>

			<span class="center col-md-3 col-sm-3 col-xs-3"><%= "#{user.first} #{user.last}" %></span>
			<span class="center col-md-5 col-sm-5 col-xs-5"><%= "#{user.email}" %></span>
			<%= link_to "Edit", edit_user_path(user), class: "center col-md-2 col-sm-2 col-xs-2" %>
			<%= link_to "Delete", user, method: :delete, data: { confirm: "Are you sure?" }, class: "center col-md-2 col-sm-2 col-xs-2" %>

		<% end %>
		<%= link_to "Create new user", new_user_path, class: "btn btn-primary btn-md col-md-2 col-sm-2 col-xs-2 col-md-offset-5 col-sm-offset-5 col-xs-offset-5", style: "margin-top: 40px;" %>
	</section>
<% else %>
	<section class="row">
		<div class="col-xs-12 col-md-8 col-sm-8 col-md-offset-2 col-sm-offset-2 col-lg-6 col-lg-offset-3 center jumbotron">
			<h1>Welcome to the User Database Manager!</h1> 
			<h2>To view or edit the database, please sign in.</h2>
			<br>
			<%= link_to "Sign in!", signin_path, class: "btn btn-lg btn-primary" %>
			<p style="margin-left: 0;">Don't have an account? <%= link_to "Sign up now", signup_path %>
		</div>
	</section>
<% end %>

app/views/users/new.html.erb
<h1>Create a new user</h1>
<%= form_for @user do |f| %>
 
  <p>
    <%= f.label :first, "First Name (required)" %>
    <%= f.text_field :first %>
  </p>

  <p>
    <%= f.label :last, "Last Name" %>
    <%= f.text_field :last %>
  </p>	
 
 	<p>
    <%= f.label :email, "Email (required)" %>
    <%= f.text_field :email %>
  </p>

  <% if @user.errors.any? %>
  	<% @user.errors.full_messages.each do |msg| %>
	  	<p class='error-messages'>
	  		<%= msg %>
	  	</p>
	  <% end %>
  <% end %>
 
  <p class='buttons'>
    <%= f.submit "Create user" %>
  </p>
 
<% end %>